# Generated by Django 3.2.9 on 2021-12-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advent', '0002_auto_20211116_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='is_commentable',
            field=models.BooleanField(default=False),
        ),
    ]
